name: Update repos

on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install git+https://github.com/itbrasil-odoo/maintainer-tools.git
      - name: Manage repositories
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          itbr-repo-manage --org $GITHUB_REPOSITORY_OWNER --conf-dir ./conf
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update checksum
          file_pattern: "conf/checksum.yml"
          commit_user_name: ITBR-git-bot
          commit_user_email: itbr-git-bot@itbrasil.com.br
          commit_author: ITBR-git-bot <itbr-git-bot@itbrasil.com.br>

